### ISSUE TITLE
Investigate setting default images in the database and not with a method

### ISSUE THREAD

**Issue by helloeduardo** [nmking22/monster_shop_2008#41]
The database default image did not work as expected when updated with an empty image string `""`. Had to create a set_default_image method, but perhaps there are better solutions?

_Originally posted by @helloeduardo in https://github.com/nmking22/monster_shop_2008/pull/40#discussion_r516975941_

**Comment by the-color-bliu** [comment]
Let's not have the default image rely on the migration, it may be best to keep the default image as a method in the controller.

**Comment by badgerbreezy** [comment]
close issue #41
